# Generated by Django 4.2.27 on 2026-01-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profile_image_url', models.TextField(blank=True)),
                ('is_welfare_worker', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
