# Generated by Django 4.2.27 on 2026-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
