# Generated by Django 4.2.27 on 2026-01-30 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_as_peer', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_as_senior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallTranscriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=5)),
                ('speaker', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_lines', to='calls.calllog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAFE', 'SAFE'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER')], default='SAFE', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='calls.calllog')),
            ],
        ),
    ]
