# Generated by Django 4.2.27 on 2026-01-30 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('MATCHED', 'MATCHED'), ('CALLING', 'CALLING'), ('ENDED', 'ENDED'), ('CANCELED', 'CANCELED')], default='WAITING', max_length=10)),
            ],
        ),
    ]
